apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-processor
  labels:
    app: backend-processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-processor
  template:
    metadata:
      labels:
        app: backend-processor
    spec:
      containers:
      - name: backend-processor
        image: backend-processor:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_RABBITMQ_HOST
          value: "rabbitmq-service"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-service:5432/middleware"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend-processor-service
spec:
  selector:
    app: backend-processor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP 