# Server Configuration
server:
  port: 8082

spring:
  profiles:
    include: shared
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    connection-timeout: 10000
    requested-heartbeat: 60
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
      retry:
        enabled: true
        max-attempts: 3
        initial-interval: 1000
        multiplier: 2.0
        max-interval: 10000
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5433/middleware_config
    username: middleware_user
    password: secure_password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public
        jdbc:
          lob:
            non_contextual_creation: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.internal.JCacheRegionFactory
          provider_class: org.ehcache.jsr107.EhcacheCachingProvider
          missing_cache_strategy: create
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
    table: flyway_schema_history
    repair-on-migrate: true
    validate-on-migrate: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  redis:
    enabled: false
  boot:
    admin:
      client:
        enabled: false
  data:
    redis:
      repositories:
        enabled: false

# AS2 Configuration
as2:
  serverId: MiddlewareAS2Server
  serverHost: localhost
  serverPort: 8082
  keyStorePath: keystore.jks
  keyStorePassword: password
  privateKeyAlias: as2key
  privateKeyPassword: password
  requestSignature: true
  requestEncryption: true
  requestMdn: true
  mdnSignature: true
  processedDirectory: processed
  errorDirectory: error
  maxRetries: 3
  retryDelay: 5000

# Service-specific Logging
logging:
  level:
    root: INFO
    com.middleware: DEBUG
    com.middleware.listener: DEBUG
    com.middleware.shared.security: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.apache.camel: INFO
    org.apache.camel.component.sftp: TRACE
    org.apache.camel.support.DefaultComponent: DEBUG
    com.middleware.listener.connectors.sftp: TRACE
    com.middleware.listener.connectors.sftp.config.SftpCamelConfig: DEBUG
    com.jcraft.jsch: TRACE
    com.jcraft.jsch.Session: DEBUG
    com.jcraft.jsch.Channel: DEBUG
    com.jcraft.jsch.ChannelSftp: DEBUG
    org.apache.camel.component.file.remote: TRACE

# SFTP Configuration
sftp:
  enabled: true
  host: localhost
  port: 22
  username: admin
  password: admin
  strictHostKeyChecking: false
  monitoredDirectories: ["inbound"]
  pollingInterval: 15000
  connectionTimeout: 30000
  maxRetries: 3
  retryDelay: 5000
  root: ./sftp_root
  processedDirectory: processed
  errorDirectory: error

management:
  health:
    redis:
      enabled: false 