# Server Configuration
server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    include: shared
  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: admin
    password: admin
    queue:
      inbound:
        processor: inbound.processor
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 5000
          max-attempts: 3
          multiplier: 2
        acknowledge-mode: manual
        prefetch: 1
        concurrency: 1
        max-concurrency: 3
    connection-factory:
      concurrent-consumers: 3
      max-concurrent-consumers: 10
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: 0
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1

# Service-specific Logging
logging:
  level:
    com.middleware.processor: DEBUG
    com.middleware.processor.service: DEBUG
    com.middleware.processor.service.impl: DEBUG
    com.middleware.processor.service.strategy: DEBUG
    com.middleware.processor.service.impl.XmlValidationServiceImpl: DEBUG
    com.middleware.processor.service.impl.XmlProcessorServiceImpl: DEBUG
    com.middleware.processor.service.strategy.AsnDocumentProcessingStrategy: DEBUG
    org.springframework.web.multipart: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    com.middleware.processor.config.CsrfTokenLoggingFilter: TRACE
    javax.xml.validation: TRACE
    org.xml.sax: TRACE

# XML Validation Configuration
xml:
  validation:
    entity-expansion-limit: ${XML_ENTITY_EXPANSION_LIMIT:0}  # 0 for unlimited
    honour-all-schema-locations: true
    enable-external-dtd: false
    enable-external-schema: false
    enable-schema-full-checking: false
    max-memory-size: 10485760  # 10MB in bytes

# SFTP Configuration
sftp:
  root: ${SFTP_ROOT:/sftp_root}

# Batch Processing Configuration
batch:
  core-pool-size: 5
  max-pool-size: 10
  queue-capacity: 25
  thread-name-prefix: BatchProcessor-
  size: 100
  timeout-seconds: 300
  min-size: 10
  max-size: 100
  queue-depth-threshold: 1000
  adjustment-step: 10

# Cache Configuration
cache:
  validation:
    ttl: 3600  # 1 hour in seconds
    max-size: 10000 